version: '3.8'
services:
  db:
    image: postgres:15-alpine3.20
    restart: always
    environment:
      - POSTGRES_DB=nestjs-db
      - POSTGRES_USER=nest-user
      - POSTGRES_PASSWORD=nest-password
    ports:
      - '5432:5432'
    volumes:
      - ../nest-js-db:/var/lib/postgresql/data
